<?php
// /includes/header.php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
    }

    if (!isset($koneksi)) {
        // Menggunakan __DIR__ untuk path yang lebih andal
            require_once __DIR__ . '/../config/database.php';
            }

            // Ambil Nama Website dari Database
            $nama_website_default = 'SmeksabaShop';
            $query_nama_web = "SELECT nilai_pengaturan FROM pengaturan WHERE nama_pengaturan = 'nama_website' LIMIT 1";
            $result_nama_web = mysqli_query($koneksi, $query_nama_web);
            if ($result_nama_web && mysqli_num_rows($result_nama_web) > 0) {
                $nama_website = mysqli_fetch_assoc($result_nama_web)['nilai_pengaturan'];
                } else {
                    $nama_website = $nama_website_default;
                    }

                    $jumlah_keranjang = !empty($_SESSION['keranjang']) ? count($_SESSION['keranjang']) : 0;
                    $jumlah_pesan = 0;
                    if (isset($_SESSION['user_id'])) {
                        $user_id = $_SESSION['user_id'];
                            $query_pesan = "SELECT COUNT(id) as total FROM pesan WHERE penerima_id = $user_id AND sudah_dibaca = 0";
                                $result_pesan = mysqli_query($koneksi, $query_pesan);
                                    if ($result_pesan) {
                                            $jumlah_pesan = mysqli_fetch_assoc($result_pesan)['total'];
                                                }
                                                }
                                                ?>
                                                <!DOCTYPE html>
                                                <html lang="id">
                                                <head>
                                                    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="/favicon.png" type="image/x-icon">
    
    <link href="<?php echo BASE_URL; ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?php echo BASE_URL; ?>/assets/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
    <?php
        // Teknik "Cache Busting" untuk memastikan file CSS terbaru yang dimuat
        $css_file_path = $_SERVER['DOCUMENT_ROOT'] . '/assets/css/style.css';
        $css_version = file_exists($css_file_path) ? filemtime($css_file_path) : '1.0';
        $store_css_version = file_exists($_SERVER['DOCUMENT_ROOT'] . '/assets/css/store.css') ? filemtime($_SERVER['DOCUMENT_ROOT'] . '/assets/css/store.css') : '1.0';
    ?>
    <link href="<?php echo BASE_URL; ?>/assets/css/style.css?v=<?php echo $css_version; ?>" rel="stylesheet">
    <link href="<?php echo BASE_URL; ?>/assets/css/store.css?v=<?php echo $store_css_version; ?>" rel="stylesheet">

    <title><?php echo isset($page_title) ? $page_title . ' - ' . htmlspecialchars($nama_website) : htmlspecialchars($nama_website); ?></title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                                                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                            <link href="<?php echo BASE_URL; ?>/assets/css/bootstrap.min.css" rel="stylesheet">
                                                                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
                                                                    <link href="<?php echo BASE_URL; ?>/assets/css/style.css" rel="stylesheet">
                                                                        <title><?php echo isset($page_title) ? $page_title . ' - ' . htmlspecialchars($nama_website) : htmlspecialchars($nama_website); ?></title>
                                                                            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                                                                                <style>
                                                                                        /* CSS BARU UNTUK FITUR CHAT */
                                                                                                .chat-list-item { display: flex; align-items: center; padding: 1rem; border-bottom: 1px solid #eee; text-decoration: none; color: #333; transition: background-color 0.2s; }
                                                                                                        .chat-list-item:hover { background-color: #f8f9fa; }
                                                                                                                .chat-list-avatar img { width: 50px; height: 50px; object-fit: cover; }
                                                                                                                        .chat-list-info { flex-grow: 1; overflow: hidden; }
                                                                                                                                .chat-list-info p { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; margin-bottom: 0; font-size: 0.9em; color: #6c757d; }
                                                                                                                                        .chat-list-meta { text-align: right; font-size: 0.8em; color: #6c757d; }
                                                                                                                                                .unread-badge { background-color: #dc3545; color: white; font-size: 0.75em; width: 20px; height: 20px; display: flex; align-items: center; justify-content: center; border-radius: 50%; margin-top: 5px; }

                                                                                                                                                        .chat-container { display: flex; flex-direction: column; height: calc(100vh - 220px); }
                                                                                                                                                                .chat-box { flex-grow: 1; background-color: #f0f2f5; overflow-y: auto; display: flex; flex-direction: column-reverse; }
                                                                                                                                                                        .chat-content { display: flex; flex-direction: column; padding: 1rem; }
                                                                                                                                                                                .chat-bubble { padding: 10px 15px; border-radius: 20px; max-width: 75%; word-wrap: break-word; margin-bottom: 5px; }
                                                                                                                                                                                        .bubble-sent { background-color: #d9fdd3; border-bottom-right-radius: 5px; align-self: flex-end; }
                                                                                                                                                                                                .bubble-received { background-color: #ffffff; border-bottom-left-radius: 5px; align-self: flex-start; }
                                                                                                                                                                                                    </style>
                                                                                                                                                                                                    </head>
                                                                                                                                                                                                    <body>

                                                                                                                                                                                                    <header class="header-nav">
                                                                                                                                                                                                        <div class="navbar-container">
                                                                                                                                                                                                                <a href="<?php echo BASE_URL; ?>/" class="nav-logo"><?php echo htmlspecialchars($nama_website); ?></a>
                                                                                                                                                                                                                        <div class="nav-search-desktop">
                                                                                                                                                                                                                                    <form action="<?php echo BASE_URL; ?>/pencarian.php" method="GET">
                                                                                                                                                                                                                                                    <input type="text" name="q" placeholder="Cari produk...">
                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        <div class="nav-user-desktop">
                                                                                                                                                                                                                                                                                                    <?php if (isset($_SESSION['user_id'])): ?>
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                    <a href="<?php echo BASE_URL; ?>/keranjang.php" class="position-relative" title="Keranjang">
                                                                                                                                                                                                                                                                                                                                                        <i class="bi bi-cart" style="font-size: 1.4rem; color: white;"></i>
                                                                                                                                                                                                                                                                                                                                                                            <?php if ($jumlah_keranjang > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                    <span class="icon-badge-notif" id="cart-count-badge-desktop"><?php echo $jumlah_keranjang; ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="<?php echo BASE_URL; ?>/pesan.php" class="position-relative" title="Pesan">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <i class="bi bi-chat-dots" style="font-size: 1.4rem; color: white;"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php if ($jumlah_pesan > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span class="icon-badge-notif"><?php echo $jumlah_pesan; ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="<?php echo BASE_URL; ?>/saya.php" title="Profil Saya">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <i class="bi bi-person" style="font-size: 1.6rem; color: white;"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="<?php echo BASE_URL; ?>/auth/logout.php" class="ms-3">Logout</a>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="<?php echo BASE_URL; ?>/auth/login.php" class="btn">Login</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="<?php echo BASE_URL; ?>/auth/register.php">Daftar</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="navbar-container-mobile">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <form class="mobile-search-form" action="<?php echo BASE_URL; ?>/pencarian.php" method="GET">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <i class="bi bi-search"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="text" name="q" placeholder="Cari...">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="mobile-nav-icons">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="<?php echo BASE_URL; ?>/keranjang.php" class="position-relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="bi bi-cart"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php if ($jumlah_keranjang > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span class="icon-badge-notif" id="cart-count-badge-mobile"><?php echo $jumlah_keranjang > 99 ? '99+' : $jumlah_keranjang; ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="<?php echo BASE_URL; ?>/pesan.php" class="position-relative"> 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <i class="bi bi-chat-dots"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php if ($jumlah_pesan > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="icon-badge-notif"><?php echo $jumlah_pesan > 99 ? '99+' : $jumlah_pesan; ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <main class="main-container">