<?php
// /includes/header_admin.php
require_once __DIR__ . '/../config/database.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: " . BASE_URL . "/auth/login.php");
        exit();
        }

        $nama_website_default = 'Shopbox Admin';
        $query_nama_web = "SELECT nilai_pengaturan FROM pengaturan WHERE nama_pengaturan = 'nama_website' LIMIT 1";
        $result_nama_web = mysqli_query($koneksi, $query_nama_web);
        $nama_website = ($result_nama_web && mysqli_num_rows($result_nama_web) > 0) ? mysqli_fetch_assoc($result_nama_web)['nilai_pengaturan'] : $nama_website_default;
        ?>
        <!DOCTYPE html>
        <html lang="id">
        <head>
            <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <link href="<?php echo BASE_URL; ?>/assets/css/bootstrap.min.css" rel="stylesheet">
                        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
                            <title><?php echo isset($page_title) ? htmlspecialchars($page_title) . ' - Admin' : 'Dashboard Admin'; ?></title>
                                <style>
                                        /* (CSS LENGKAP DARI JAWABAN SEBELUMNYA ADA DI SINI) */
                                                body { display: flex; background-color: #f8f9fa; }
                                                        .top-bar { background-color: #343a40; color: white; padding: 0.75rem 1rem; position: fixed; top: 0; left: 0; width: 100%; z-index: 1030; display: flex; align-items: center; box-shadow: 0 2px 4px rgba(0,0,0,.1); }
                                                                .menu-toggle { font-size: 1.5rem; background: none; border: none; color: white; margin-right: 1rem; }
                                                                        .sidebar { width: 250px; min-height: 100vh; background-color: #343a40; position: fixed; top: 0; left: 0; transform: translateX(-250px); transition: transform 0.3s ease-in-out; z-index: 1040; padding-top: 60px; }
                                                                                .sidebar.show { transform: translateX(0); }
                                                                                        .sidebar .nav-link { color: #c2c7d0; padding: .85rem 1.2rem; border-left: 3px solid transparent; display: flex; align-items: center; }
                                                                                                .sidebar .nav-link .bi { margin-right: 0.8rem; font-size: 1.1rem; }
                                                                                                        .sidebar .nav-link:hover, .sidebar .nav-link.active { color: #fff; background-color: #495057; border-left: 3px solid #0d6efd; }
                                                                                                                .sidebar .dropdown-menu { background-color: #495057; border: none; }
                                                                                                                        .sidebar .dropdown-item { color: #c2c7d0; padding-left: 2.5rem; }
                                                                                                                                .sidebar .dropdown-item:hover { color: #fff; background-color: #5a6268; }
                                                                                                                                        .content-wrapper { flex-grow: 1; padding: 20px; padding-top: 80px; width: 100%; margin-left: 0; transition: margin-left 0.3s ease-in-out; }
                                                                                                                                                @media (min-width: 992px) { .sidebar { transform: translateX(0); } .content-wrapper { margin-left: 250px; } .menu-toggle { display: none; } }
                                                                                                                                                        @media (max-width: 991.98px) { .sidebar.show + .overlay + .content-wrapper { margin-left: 0; } }
                                                                                                                                                                .overlay { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0,0,0,0.5); z-index: 1035; }
                                                                                                                                                                        .overlay.show { display: block; }
                                                                                                                                                                            </style>
                                                                                                                                                                            </head>
                                                                                                                                                                            <body>

                                                                                                                                                                            <div class="top-bar no-print">
                                                                                                                                                                                <button class="menu-toggle" id="menuToggle">☰</button>
                                                                                                                                                                                    <h5 class="mb-0"><?php echo htmlspecialchars($nama_website); ?> Admin Panel</h5>
                                                                                                                                                                                    </div>

                                                                                                                                                                                    <div class="sidebar no-print" id="adminSidebar">
                                                                                                                                                                                        <ul class="nav flex-column">
                                                                                                                                                                                                <li class="nav-item"><a class="nav-link" href="<?php echo BASE_URL; ?>/admin/index.php"><i class="bi bi-speedometer2"></i> Dashboard</a></li>
                                                                                                                                                                                                        <li class="nav-item"><a class="nav-link" href="<?php echo BASE_URL; ?>/admin/kelola_pesanan.php"><i class="bi bi-box-seam"></i> Kelola Pesanan</a></li>
                                                                                                                                                                                                                <li class="nav-item"><a class="nav-link" href="<?php echo BASE_URL; ?>/admin/kelola_produk.php"><i class="bi bi-kanban"></i> Moderasi Produk</a></li>
                                                                                                                                                                                                                        <li class="nav-item"><a class="nav-link" href="<?php echo BASE_URL; ?>/admin/kelola_pengguna.php"><i class="bi bi-people"></i> Kelola Pengguna</a></li>
                                                                                                                                                                                                                                <li class="nav-item"><a class="nav-link" href="<?php echo BASE_URL; ?>/admin/kelola_toko.php"><i class="bi bi-shop"></i> Kelola Toko</a></li>
                                                                                                                                                                                                                                        <li class="nav-item"><a class="nav-link" href="<?php echo BASE_URL; ?>/admin/kelola_verifikasi.php"><i class="bi bi-patch-check"></i> Verifikasi Penjual</a></li>
                                                                                                                                                                                                                                                <li class="nav-item dropdown">
                                                                                                                                                                                                                                                            <a class="nav-link dropdown-toggle" href="#" id="keuanganDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-wallet2"></i> Keuangan</a>
                                                                                                                                                                                                                                                                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="keuanganDropdown">
                                                                                                                                                                                                                                                                                        <li><a class="dropdown-item" href="<?php echo BASE_URL; ?>/admin/saldo_admin.php">Saldo Admin</a></li>
                                                                                                                                                                                                                                                                                                        <li><a class="dropdown-item" href="<?php echo BASE_URL; ?>/admin/saldo_negatif.php">Pantau Saldo Negatif</a></li>
                                                                                                                                                                                                                                                                                                                        <li><a class="dropdown-item" href="<?php echo BASE_URL; ?>/admin/penarikan_dana.php">Penarikan Dana</a></li>
                                                                                                                                                                                                                                                                                                                                        <li><a class="dropdown-item" href="<?php echo BASE_URL; ?>/admin/laporan_keuangan_admin.php">Laporan Keuangan</a></li>
                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                    <li class="nav-item dropdown">
                                                                                                                                                                                                                                                                                                                                                                                <a class="nav-link dropdown-toggle" href="#" id="pengaturanDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-gear"></i> Pengaturan Situs</a>
                                                                                                                                                                                                                                                                                                                                                                                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="pengaturanDropdown">
                                                                                                                                                                                                                                                                                                                                                                                                            <li><a class="dropdown-item" href="<?php echo BASE_URL; ?>/admin/kelola_pengaturan.php">Pengaturan Umum</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                            <li><a class="dropdown-item" href="<?php echo BASE_URL; ?>/admin/kelola_kategori.php">Kelola Kategori</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <li><a class="dropdown-item" href="<?php echo BASE_URL; ?>/admin/kelola_banner.php">Kelola Banner</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li><a class="dropdown-item" href="<?php echo BASE_URL; ?>/admin/kelola_ongkir.php">Kelola Ongkir</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li class="nav-item mt-4 border-top pt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a class="nav-link" href="<?php echo BASE_URL; ?>/"><i class="bi bi-arrow-left-square"></i> Kembali ke Situs</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li class="nav-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a class="nav-link" href="<?php echo BASE_URL; ?>/auth/logout.php"><i class="bi bi-box-arrow-right"></i> Logout</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="overlay no-print" id="overlay"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="content-wrapper">