<?php
// /kategori.php
// Tambahkan baris ini untuk menampilkan semua error PHP
error_reporting(E_ALL);
ini_set('display_errors', 1);

if (!isset($_GET['id']) || empty($_GET['id'])) {
    header("Location: /index.php");
        exit();
        }

        $kategori_id = (int)$_GET['id'];
        require_once 'config/database.php';
        require_once 'includes/functions.php';

        // --- BAGIAN DEBUGGING 1: Cek Query Kategori ---
        $stmt_kat = $koneksi->prepare("SELECT nama_kategori FROM kategori WHERE id = ?");
        if ($stmt_kat === false) {
            die('Error prepare statement kategori: ' . $koneksi->error);
            }
            $stmt_kat->bind_param("i", $kategori_id);
            if (!$stmt_kat->execute()) {
                die('Error execute statement kategori: ' . $stmt_kat->error);
                }

                $result_kat = $stmt_kat->get_result();
                if ($result_kat->num_rows === 0) {
                    header("Location: /index.php");
                        exit();
                        }
                        $kategori = $result_kat->fetch_assoc();
                        $page_title = "Kategori: " . htmlspecialchars($kategori['nama_kategori']);
                        $stmt_kat->close();

                        require_once 'includes/header.php';
                        ?>

                        <h1 class="mb-4">Produk Kategori: <?php echo htmlspecialchars($kategori['nama_kategori']); ?></h1>

                        <div class="product-grid">
                            <?php
                                // --- BAGIAN DEBUGGING 2: Cek Query Produk ---
                                    $query_produk = "
                                            SELECT produk.*, t.nama_toko 
                                                    FROM produk 
                                                            JOIN toko t ON produk.toko_id = t.id
                                                                    WHERE produk.status_moderasi = 'disetujui' AND produk.kategori_id = ? AND t.is_active = 1
                                                                            ORDER BY produk.created_at DESC
                                                                                ";

                                                                                    $stmt = $koneksi->prepare($query_produk);
                                                                                        if ($stmt === false) {
                                                                                                die('Error prepare statement produk: ' . $koneksi->error);
                                                                                                    }
                                                                                                        
                                                                                                            $stmt->bind_param("i", $kategori_id);
                                                                                                                if (!$stmt->execute()) {
                                                                                                                        die('Error execute statement produk: ' . $stmt->error);
                                                                                                                            }

                                                                                                                                $result_produk = $stmt->get_result();

                                                                                                                                    if ($result_produk && mysqli_num_rows($result_produk) > 0):
                                                                                                                                            while ($produk = mysqli_fetch_assoc($result_produk)):
                                                                                                                                                        $promo_data = getEffectivePriceAndPromoStatus($produk);
                                                                                                                                                            ?>
                                                                                                                                                                        <div class="col">
                                                                                                                                                                                        <div class="card h-100 shadow-sm">
                                                                                                                                                                                                            <a href="detail_produk.php?id=<?php echo $produk['id']; ?>">
                                                                                                                                                                                                                                    <img src="/uploads/produk/<?php echo htmlspecialchars($produk['gambar_produk']); ?>" class="card-img-top" alt="<?php echo htmlspecialchars($produk['nama_produk']); ?>" style="height: 200px; object-fit: cover;">
                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                            <div class="card-body d-flex flex-column">
                                                                                                                                                                                                                                                                                                    <h5 class="card-title">
                                                                                                                                                                                                                                                                                                                                <a href="detail_produk.php?id=<?php echo $produk['id']; ?>" class="text-decoration-none text-dark stretched-link">
                                                                                                                                                                                                                                                                                                                                                                <?php echo htmlspecialchars(substr($produk['nama_produk'], 0, 50)); ?>
                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                    </h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p class="card-text text-muted small mt-auto"><?php echo htmlspecialchars($produk['nama_toko']); ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php if ($promo_data['is_promo'] || $promo_data['promo_text']): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p class="card-subtitle mb-0 text-danger fw-bold">Rp <?php echo number_format($promo_data['price'], 0, ',', '.'); ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p class="card-text text-muted"><del>Rp <?php echo number_format($promo_data['harga_normal'], 0, ',', '.'); ?></del></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php if ($promo_data['promo_text']): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span class="badge <?php echo $promo_data['promo_badge_class']; ?>"><?php echo $promo_data['promo_text']; ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h6 class="card-subtitle mb-2 text-danger fw-bold">Rp <?php echo number_format($promo_data['price'], 0, ',', '.'); ?></h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            endwhile;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="col-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="alert alert-info">Belum ada produk dalam kategori ini.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        endif;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                require_once 'includes/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>