<?php
// /admin/kelola_kategori.php
$page_title = "Kelola Kategori";
require_once '../includes/header_admin.php';

// Ambil semua kategori
$result = mysqli_query($koneksi, "SELECT * FROM kategori ORDER BY nama_kategori ASC");
?>

<h1>Kelola Kategori Produk</h1>
<p>Tambah, edit, atau hapus kategori produk.</p>

<?php 
if (isset($_GET['status'])) {
    if ($_GET['status'] == 'sukses') echo '<div class="alert alert-success">Operasi kategori berhasil.</div>';
        else echo '<div class="alert alert-danger">Operasi kategori gagal.</div>';
        }
        ?>

        <div class="row">
            <div class="col-md-4">
                    <div class="card shadow-sm">
                                <div class="card-header">Tambah Kategori Baru</div>
                                            <div class="card-body">
                                                            <form action="proses_kategori.php" method="POST" enctype="multipart/form-data">
                                                                                <input type="hidden" name="action" value="tambah">
                                                                                                    <div class="mb-3">
                                                                                                                            <label for="nama_kategori" class="form-label">Nama Kategori</label>
                                                                                                                                                    <input type="text" name="nama_kategori" id="nama_kategori" class="form-control" required>
                                                                                                                                                                        </div>
                                                                                                                                                                                            <div class="mb-3">
                                                                                                                                                                                                                    <label for="icon_kategori" class="form-label">Ikon Kategori (Opsional, PNG/SVG)</label>
                                                                                                                                                                                                                                            <input type="file" name="icon_kategori" id="icon_kategori" class="form-control" accept="image/png,image/svg+xml">
                                                                                                                                                                                                                                                                    <div class="form-text">Ukuran ikon idealnya kecil, misalnya 32x32px. Disarankan format PNG atau SVG.</div>
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                            <button type="submit" class="btn btn-primary">Tambah</button>
                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                        <div class="col-md-8">
                                                                                                                                                                                                                                                                                                                                                                <div class="card shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                            <div class="card-header">Daftar Kategori</div>
                                                                                                                                                                                                                                                                                                                                                                                        <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                         <table class="table table-bordered">
                                                                                                                                                                                                                                                                                                                                                                                                                             <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                     <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <th>Ikon</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <th>Nama Kategori</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <th>Aksi</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <?php while($kategori = mysqli_fetch_assoc($result)): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <?php if (!empty($kategori['icon'])): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <img src="<?php echo htmlspecialchars($kategori['icon']); ?>" alt="<?php echo htmlspecialchars($kategori['nama_kategori']); ?>" width="32" height="32">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <td><?php echo htmlspecialchars($kategori['nama_kategori']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <form action="proses_kategori.php" method="POST" class="d-inline" onsubmit="return confirm('Yakin ingin hapus kategori ini? Tindakan ini tidak dapat dibatalkan dan akan memengaruhi produk yang menggunakan kategori ini.');">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <input type="hidden" name="action" value="hapus">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <input type="hidden" name="id" value="<?php echo $kategori['id']; ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <input type="hidden" name="icon_path" value="<?php echo htmlspecialchars($kategori['icon']); ?>"> <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <?php require_once '../includes/footer_admin.php'; ?>