<?php
// /penjual/lengkapi_alamat_toko.php
$page_title = "Lengkapi Alamat Toko";
require_once '../includes/header_penjual.php';

$user_id = $_SESSION['user_id'];
$query_toko = "SELECT nama_toko, is_smkn1_location, provinsi FROM toko WHERE user_id = ?";
$stmt_toko = $koneksi->prepare($query_toko);
$stmt_toko->bind_param("i", $user_id);
$stmt_toko->execute();
$toko = $stmt_toko->get_result()->fetch_assoc();
$stmt_toko->close();

if (isset($toko['provinsi']) && !empty($toko['provinsi'])) {
    header("Location: " . BASE_URL . "/penjual/index.php");
        exit();
        }

        $is_smkn1_location = (bool)$toko['is_smkn1_location'];
        ?>

        <div class="container">
            <div class="row justify-content-center">
                    <div class="col-lg-8">
                                <div class="card shadow-sm">
                                                <div class="card-header bg-primary text-white">
                                                                    <h4 class="mb-0">Lengkapi Alamat Toko Anda</h4>
                                                                                    </div>
                                                                                                    <div class="card-body">
                                                                                                                        <p class="lead">
                                                                                                                                                Untuk dapat mulai berjualan, Anda wajib melengkapi alamat toko secara akurat. Alamat ini akan digunakan untuk pengiriman barang.
                                                                                                                                                                    </p>
                                                                                                                                                                                        
                                                                                                                                                                                                            <?php if (isset($_GET['status']) && $_GET['status'] == 'gagal'): ?>
                                                                                                                                                                                                                                    <div class="alert alert-danger"><?php echo htmlspecialchars($_GET['pesan']); ?></div>
                                                                                                                                                                                                                                                        <?php endif; ?>

                                                                                                                                                                                                                                                                            <form action="proses_lengkapi_alamat.php" method="POST">
                                                                                                                                                                                                                                                                                                    <input type="hidden" name="toko_id" value="<?php echo $toko['id']; ?>">
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                    <div class="mb-3"><label for="provinsi" class="form-label">Provinsi</label><select class="form-select" id="provinsi" name="provinsi" required><option value="">-- Pilih Provinsi --</option></select></div>
                                                                                                                                                                                                                                                                                                                                                                            <div class="mb-3"><label for="kota" class="form-label">Kota/Kabupaten</label><select class="form-select" id="kota" name="kota" disabled required><option value="">Pilih provinsi terlebih dahulu</option></select></div>
                                                                                                                                                                                                                                                                                                                                                                                                    <div class="mb-3"><label for="kecamatan" class="form-label">Kecamatan</label><select class="form-select" id="kecamatan" name="kecamatan" disabled required><option value="">Pilih kota terlebih dahulu</option></select></div>
                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="mb-3"><label for="kelurahan" class="form-label">Kelurahan/Desa</label><input type="text" class="form-control" id="kelurahan" name="kelurahan" required></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="mb-3"><label for="alamat_lengkap" class="form-label">Alamat Lengkap (Nama Jalan, Nomor)</label><textarea class="form-control" id="alamat_lengkap" name="alamat_lengkap" rows="3" required></textarea></div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="d-grid mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" class="btn btn-success">Simpan Alamat Toko</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $(document).ready(function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $('#provinsi, #kota, #kecamatan').select2({ theme: "bootstrap-5" });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $.get('<?php echo BASE_URL; ?>/api_alamat.php?get=provinsi', data => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $('#provinsi').empty().append('<option value="">-- Pilih Provinsi --</option>');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $.each(data, (key, value) => $('#provinsi').append($('<option>', { value: value, text: value })));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, 'json');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $('#provinsi').on('change', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const prov = $(this).val();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $('#kota').empty().append('<option value="">Pilih provinsi...</option>').prop('disabled', true).trigger('change');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $('#kecamatan').empty().append('<option value="">Pilih kota...</option>').prop('disabled', true).trigger('change');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (prov) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $.get(`<?php echo BASE_URL; ?>/api_alamat.php?get=kota&provinsi=${encodeURIComponent(prov)}`, data => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $('#kota').empty().append('<option value="">-- Pilih Kota/Kabupaten --</option>');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $.each(data, (key, value) => $('#kota').append($('<option>', { value: value, text: value })));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $('#kota').prop('disabled', false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, 'json');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $('#kota').on('change', function() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const prov = $('#provinsi').val();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const kota = $(this).val();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $('#kecamatan').empty().append('<option value="">Pilih kota...</option>').prop('disabled', true).trigger('change');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (prov && kota) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $.get(`<?php echo BASE_URL; ?>/api_alamat.php?get=kecamatan&provinsi=${encodeURIComponent(prov)}&kota=${encodeURIComponent(kota)}`, data => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(data.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $('#kecamatan').empty().append('<option value="">-- Pilih Kecamatan --</option>');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $.each(data, (key, value) => $('#kecamatan').append($('<option>', { value: value, text: value })));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $('#kecamatan').prop('disabled', false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $('#kecamatan').empty().append('<option value="">-</option>').prop('disabled', true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, 'json');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </script>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php require_once '../includes/footer_penjual.php'; ?>