<?php 
// /auth/login.php

require_once '../config/database.php';

// Ambil Nama dan Logo Website dari Database
$nama_website = 'Shopmax'; // Default
$logo_website = '/uploads/logo/default_logo.png'; // Default

$result_pengaturan = mysqli_query($koneksi, "SELECT nama_pengaturan, nilai_pengaturan FROM pengaturan WHERE nama_pengaturan IN ('nama_website', 'website_logo')");
while ($row = mysqli_fetch_assoc($result_pengaturan)) {
    if ($row['nama_pengaturan'] == 'nama_website') {
            $nama_website = $row['nilai_pengaturan'];
                }
                    if ($row['nama_pengaturan'] == 'website_logo') {
                            $logo_website = $row['nilai_pengaturan'];
                                }
                                }

                                $page_title = "Login";
                                require_once '../includes/header_auth.php'; 
                                ?>

                                <div class="container mt-5">
                                    <div class="row justify-content-center">
                                            <div class="col-md-6 col-lg-4">
                                                        
                                                                    <div class="text-center mb-4">
                                                                                      <img src="<?php echo htmlspecialchars($logo_website); ?>" alt="Logo <?php echo htmlspecialchars($nama_website); ?>" style="max-width: 175px; height: auto;">
                                                                                                                                                                                    </div>

                                                                                                            <div class="card shadow-sm">
                                                                                                                            <div class="card-header text-center text-white" style="background-color: #EE4D2D;">
                                                                                                                                                <h3>Login <?php echo htmlspecialchars($nama_website); ?></h3>
                                                                                                                                                                </div>
                                                                                                                                                                                <div class="card-body">
                                                                                                                                                                                                    <?php 
                                                                                                                                                                                                                        if (isset($_GET['error'])) {
                                                                                                                                                                                                                                                $error_msg = 'Username atau password salah.';
                                                                                                                                                                                                                                                                        if ($_GET['error'] === 'dinonaktifkan') {
                                                                                                                                                                                                                                                                                                    $error_msg = 'Akun Anda telah dinonaktifkan. Silakan hubungi administrator.';
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                    echo '<div class="alert alert-danger">' . $error_msg . '</div>';
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                            if (isset($_GET['success'])) {
                                                                                                                                                                                                                                                                                                                                                                                                                    echo '<div class="alert alert-success">' . htmlspecialchars($_GET['success']) . '</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (isset($_GET['logout'])) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo '<div class="alert alert-info">Anda telah berhasil logout.</div>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <form action="proses_login.php" method="POST">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label for="username" class="form-label">Username</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="text" class="form-control" id="username" name="username" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label for="password" class="form-label">Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="password" class="form-control" id="password" name="password" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                   <div class="d-flex justify-content-end mb-3">
                                                                                                                                                                                                                                                                                                                                                                       <a href="lupa_password.php">Lupa Password?</a>
                                                                                                                                                                                                                                                                                                                                                                       </div>                                                                                                                                                                                                                                                                                                                                                                                                                     <div class="d-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit" class="btn" style="background-color: #EE4D2D; color: white;">Login</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="text-center mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Belum punya akun? <a href="register.php">Daftar di sini</a></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        require_once '../includes/footer_auth.php'; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?>