<?php
$page_title = "Lupa Password";
require_once '../includes/header_auth.php';
?>
<div class="container mt-5">
    <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                        <div class="card shadow-sm">
                                        <div class="card-header text-center">
                                                            <h3>Reset Password</h3>
                                                                            </div>
                                                                                            <div class="card-body">
                                                                                                                <?php if(isset($_GET['status'])): ?>
                                                                                                                                        <div class="alert alert-<?php echo $_GET['status'] == 'sukses' ? 'success' : 'danger'; ?>">
                                                                                                                                                                    <?php echo htmlspecialchars($_GET['pesan']); ?>
                                                                                                                                                                                            </div>
                                                                                                                                                                                                                <?php endif; ?>
                                                                                                                                                                                                                                    <p class="text-muted">Masukkan alamat email Anda yang terdaftar. Kami akan mengirimkan link untuk mereset password Anda.</p>
                                                                                                                                                                                                                                                        <form action="proses_lupa_password.php" method="POST">
                                                                                                                                                                                                                                                                                <div class="mb-3">
                                                                                                                                                                                                                                                                                                            <label for="email" class="form-label">Email</label>
                                                                                                                                                                                                                                                                                                                                        <input type="email" class="form-control" id="email" name="email" required>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                        <div class="d-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit" class="btn btn-primary">Kirim Link Reset</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="text-center mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="login.php">Kembali ke Login</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php require_once '../includes/footer_auth.php'; ?>