<?php
// /notifikasi.php (Versi Perbaikan)

// Atur judul halaman
$page_title = "Notifikasi";

// Panggil header.php, ini akan membuat koneksi ($koneksi) dan memulai session
require_once 'includes/header.php';

// Pastikan user sudah login
if (!isset($_SESSION['user_id'])) {
    header("Location: /auth/login.php");
        exit();
        }
        $user_id = $_SESSION['user_id'];
        $user_role = $_SESSION['role'];

        // --- Ambil Notifikasi untuk PEMBELI ---
        $stmt_pembeli = $koneksi->prepare("SELECT * FROM notifikasi WHERE user_id = ? AND tipe = 'pembeli' ORDER BY created_at DESC");
        $stmt_pembeli->bind_param("i", $user_id);
        $stmt_pembeli->execute();
        $notif_pembeli = $stmt_pembeli->get_result();

        // --- Jika user adalah PENJUAL, ambil juga notifikasi toko ---
        $notif_penjual = null; // Inisialisasi variabel
        if ($user_role == 'penjual') {
            $stmt_penjual = $koneksi->prepare("SELECT * FROM notifikasi WHERE user_id = ? AND tipe = 'penjual' ORDER BY created_at DESC");
                $stmt_penjual->bind_param("i", $user_id);
                    $stmt_penjual->execute();
                        $notif_penjual = $stmt_penjual->get_result();
                        }

                        ?>

                        <div class="container">
                            <h3 class="mb-3">Notifikasi</h3>

                                <ul class="nav nav-tabs" id="notifTab" role="tablist">
                                        <li class="nav-item" role="presentation">
                                                    <button class="nav-link active" id="pembeli-tab" data-bs-toggle="tab" data-bs-target="#pembeli" type="button" role="tab">Notifikasi Saya</button>
                                                            </li>
                                                                    <?php if ($user_role == 'penjual'): ?>
                                                                            <li class="nav-item" role="presentation">
                                                                                        <button class="nav-link" id="penjual-tab" data-bs-toggle="tab" data-bs-target="#penjual" type="button" role="tab">Notifikasi Toko</button>
                                                                                                </li>
                                                                                                        <?php endif; ?>
                                                                                                            </ul>

                                                                                                                <div class="tab-content" id="notifTabContent">
                                                                                                                        <div class="tab-pane fade show active" id="pembeli" role="tabpanel">
                                                                                                                                    <ul class="list-group list-group-flush mt-2">
                                                                                                                                                    <?php if ($notif_pembeli->num_rows > 0): ?>
                                                                                                                                                                        <?php while($notif = $notif_pembeli->fetch_assoc()): ?>
                                                                                                                                                                                                <li class="list-group-item">
                                                                                                                                                                                                                            <a href="<?php echo htmlspecialchars($notif['link'] ?? '#'); ?>" class="text-decoration-none text-dark d-block">
                                                                                                                                                                                                                                                            <div class="d-flex w-100 justify-content-between">
                                                                                                                                                                                                                                                                                                <h6 class="mb-1"><?php echo htmlspecialchars($notif['judul']); ?></h6>
                                                                                                                                                                                                                                                                                                                                    <small class="text-muted"><?php echo date('d M Y', strtotime($notif['created_at'])); ?></small>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                    <p class="mb-1"><?php echo htmlspecialchars($notif['pesan']); ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li class="list-group-item text-center p-4">Belum ada notifikasi.</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php if ($user_role == 'penjual'): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="tab-pane fade" id="penjual" role="tabpanel">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ul class="list-group list-group-flush mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <?php if ($notif_penjual && $notif_penjual->num_rows > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <?php while($notif = $notif_penjual->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <li class="list-group-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <a href="<?php echo htmlspecialchars($notif['link'] ?? '#'); ?>" class="text-decoration-none text-dark d-block">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div class="d-flex w-100 justify-content-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <h6 class="mb-1"><?php echo htmlspecialchars($notif['judul']); ?></h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <small class="text-muted"><?php echo date('d M Y', strtotime($notif['created_at'])); ?></small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p class="mb-1"><?php echo htmlspecialchars($notif['pesan']); ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <li class="list-group-item text-center p-4">Belum ada notifikasi toko.</li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Panggil footer untuk menampilkan menu bawah
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             require_once 'includes/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ?>