<?php
// /pencarian.php
if (!isset($_GET['q']) || empty(trim($_GET['q']))) {
    header("Location: index.php");
        exit();
        }

        $search_query = trim($_GET['q']);
        $page_title = "Hasil Pencarian untuk: " . htmlspecialchars($search_query);
        require_once 'includes/header.php';
        require_once 'includes/functions.php'; // Panggil file fungsi terpusat

        $param = "%" . $search_query . "%";
        $stmt = $koneksi->prepare("
            SELECT produk.*, toko.nama_toko 
                FROM produk 
                    JOIN toko ON produk.toko_id = toko.id
                        WHERE (produk.nama_produk LIKE ? OR produk.deskripsi LIKE ?)
                            AND produk.status_moderasi = 'disetujui'
                                AND toko.is_active = 1
                                ");
                                $stmt->bind_param("ss", $param, $param);
                                $stmt->execute();
                                $result_produk = $stmt->get_result();
                                ?>

                                <h2 class="mb-4">Hasil Pencarian untuk: "<?php echo htmlspecialchars($search_query); ?>"</h2>
                                <p><?php echo $result_produk->num_rows; ?> produk ditemukan.</p>
                                <hr>

                                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4">
                                    <?php if ($result_produk->num_rows > 0): ?>
                                            <?php while ($produk = $result_produk->fetch_assoc()): 
                                                        $promo_data = getEffectivePriceAndPromoStatus($produk); // Fungsi ini dari functions.php
                                                                ?>
                                                                        <div class="col">
                                                                                    <div class="card h-100 shadow-sm">
                                                                                                    <a href="detail_produk.php?id=<?php echo $produk['id']; ?>">
                                                                                                                        <img src="/uploads/produk/<?php echo htmlspecialchars($produk['gambar_produk']); ?>" class="card-img-top" alt="<?php echo htmlspecialchars($produk['nama_produk']); ?>" style="height: 200px; object-fit: cover;">
                                                                                                                                        </a>
                                                                                                                                                        <div class="card-body">
                                                                                                                                                                            <h5 class="card-title"><a href="detail_produk.php?id=<?php echo $produk['id']; ?>" class="text-decoration-none text-dark"><?php echo htmlspecialchars($produk['nama_produk']); ?></a></h5>
                                                                                                                                                                                                <p class="card-text text-muted small"><?php echo htmlspecialchars($produk['nama_toko']); ?></p>
                                                                                                                                                                                                                    <?php if ($promo_data['is_promo'] || $promo_data['promo_text']): ?>
                                                                                                                                                                                                                                            <p class="card-subtitle mb-0 text-danger fw-bold">Rp <?php echo number_format($promo_data['price'], 0, ',', '.'); ?></p>
                                                                                                                                                                                                                                                                    <p class="card-text text-muted"><del>Rp <?php echo number_format($promo_data['harga_normal'], 0, ',', '.'); ?></del></p>
                                                                                                                                                                                                                                                                                            <?php if ($promo_data['promo_text']): ?>
                                                                                                                                                                                                                                                                                                                        <span class="badge <?php echo $promo_data['promo_badge_class']; ?>"><?php echo $promo_data['promo_text']; ?></span>
                                                                                                                                                                                                                                                                                                                                                <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                    <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                            <h6 class="card-subtitle mb-2 text-danger fw-bold">Rp <?php echo number_format($promo_data['price'], 0, ',', '.'); ?></h6>
                                                                                                                                                                                                                                                                                                                                                                                                                <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="card-footer bg-white border-top-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="detail_produk.php?id=<?php echo $produk['id']; ?>" class="btn btn-outline-primary w-100">Lihat Detail</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="col-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="alert alert-warning">Produk yang Anda cari tidak ditemukan. Coba kata kunci lain.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    require_once 'includes/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?>