<?php
// /produk.php
$page_title = "Semua Produk";
require_once 'includes/header.php';
require_once 'includes/functions.php'; // Panggil file fungsi terpusat

$halaman_aktif = isset($_GET['halaman']) ? (int)$_GET['halaman'] : 1;
$limit = 12;
$offset = ($halaman_aktif - 1) * $limit;

$query_total = "SELECT COUNT(p.id) as total FROM produk p JOIN toko t ON p.toko_id = t.id WHERE p.status_moderasi = 'disetujui' AND t.is_active = 1";
$result_total = mysqli_query($koneksi, $query_total);
$total_produk = mysqli_fetch_assoc($result_total)['total'];
$total_halaman = ceil($total_produk / $limit);
?>

<h1 class="mb-4">Semua Produk</h1>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
    <?php
        $query_produk = "
                SELECT produk.*, toko.nama_toko 
                        FROM produk 
                                JOIN toko ON produk.toko_id = toko.id
                                        WHERE produk.status_moderasi = 'disetujui' AND toko.is_active = 1
                                                ORDER BY produk.created_at DESC
                                                        LIMIT ? OFFSET ?
                                                            ";
                                                                    
                                                                        $stmt = $koneksi->prepare($query_produk);
                                                                            $stmt->bind_param("ii", $limit, $offset);
                                                                                $stmt->execute();
                                                                                    $result_produk = $stmt->get_result();
                                                                                            
                                                                                                if ($result_produk && mysqli_num_rows($result_produk) > 0):
                                                                                                        while ($produk = mysqli_fetch_assoc($result_produk)):
                                                                                                                    $promo_data = getEffectivePriceAndPromoStatus($produk); // Fungsi ini dari functions.php
                                                                                                                        ?>
                                                                                                                            <div class="col">
                                                                                                                                    <div class="card h-100 shadow-sm">
                                                                                                                                                <a href="detail_produk.php?id=<?php echo $produk['id']; ?>">
                                                                                                                                                                <img src="/uploads/produk/<?php echo htmlspecialchars($produk['gambar_produk']); ?>" class="card-img-top" alt="<?php echo htmlspecialchars($produk['nama_produk']); ?>" style="height: 200px; object-fit: cover;">
                                                                                                                                                                            </a>
                                                                                                                                                                                        <div class="card-body d-flex flex-column">
                                                                                                                                                                                                        <h5 class="card-title">
                                                                                                                                                                                                                            <a href="detail_produk.php?id=<?php echo $produk['id']; ?>" class="text-decoration-none text-dark stretched-link">
                                                                                                                                                                                                                                                    <?php echo htmlspecialchars(substr($produk['nama_produk'], 0, 50)); ?>
                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                        </h5>

<p class="card-text text-muted small mt-auto">
    <a href="detail_toko_pembeli.php?id=<?php echo $produk['toko_id']; ?>" class="text-muted text-decoration-none">
        <?php echo htmlspecialchars($produk['nama_toko']); ?>
    </a>
</p>
                                                                                                                                                                                                                                                                                                                        <?php if ($promo_data['is_promo'] || $promo_data['promo_text']): ?>
                                                                                                                                                                                                                                                                                                                                            <p class="card-subtitle mb-0 text-danger fw-bold">Rp <?php echo number_format($promo_data['price'], 0, ',', '.'); ?></p>
                                                                                                                                                                                                                                                                                                                                                                <p class="card-text text-muted"><del>Rp <?php echo number_format($promo_data['harga_normal'], 0, ',', '.'); ?></del></p>
                                                                                                                                                                                                                                                                                                                                                                                    <?php if ($promo_data['promo_text']): ?>
                                                                                                                                                                                                                                                                                                                                                                                                            <span class="badge <?php echo $promo_data['promo_badge_class']; ?>"><?php echo $promo_data['promo_text']; ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h6 class="card-subtitle mb-2 text-danger fw-bold">Rp <?php echo number_format($promo_data['price'], 0, ',', '.'); ?></h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        endwhile;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="col-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="alert alert-info">Tidak ada produk yang tersedia saat ini.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        endif;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <nav aria-label="Navigasi Halaman Produk" class="mt-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ul class="pagination justify-content-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php if ($halaman_aktif > 1): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li class="page-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a class="page-link" href="?halaman=<?php echo $halaman_aktif - 1; ?>">Sebelumnya</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endif; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php for ($i = 1; $i <= $total_halaman; $i++): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li class="page-item <?php if ($i == $halaman_aktif) echo 'active'; ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a class="page-link" href="?halaman=<?php echo $i; ?>"><?php echo $i; ?></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endfor; ?>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php if ($halaman_aktif < $total_halaman): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li class="page-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a class="page-link" href="?halaman=<?php echo $halaman_aktif + 1; ?>">Berikutnya</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                require_once 'includes/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>