<?php
// proses_update_keranjang.php
session_start(); // Pastikan session dimulai
require_once 'config/database.php'; // Panggil koneksi database

header('Content-Type: application/json'); // Beri tahu browser bahwa responsnya adalah JSON

$response = ['success' => false, 'message' => ''];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!isset($_SESSION['user_id'])) {
            $response['message'] = 'Anda harus login untuk memperbarui keranjang.';
                    echo json_encode($response);
                            exit();
                                }

                                    $produk_id = isset($_POST['produk_id']) ? (int)$_POST['produk_id'] : 0;
                                        $jumlah_baru = isset($_POST['jumlah']) ? (int)$_POST['jumlah'] : 0;

                                            if ($produk_id <= 0 || $jumlah_baru < 0) { // Jumlah bisa 0 jika ingin menghapus
                                                    $response['message'] = 'Data produk tidak valid.';
                                                            echo json_encode($response);
                                                                    exit();
                                                                        }

                                                                            if (!isset($_SESSION['keranjang'])) {
                                                                                    $_SESSION['keranjang'] = [];
                                                                                        }

                                                                                            // Ambil detail produk dari database untuk mendapatkan harga
                                                                                                $query_produk = "SELECT harga, harga_diskon, promo_mulai, promo_akhir FROM produk WHERE id = ?";
                                                                                                    $stmt = mysqli_prepare($koneksi, $query_produk);
                                                                                                        mysqli_stmt_bind_param($stmt, "i", $produk_id);
                                                                                                            mysqli_stmt_execute($stmt);
                                                                                                                $result_produk = mysqli_stmt_get_result($stmt);
                                                                                                                    $produk_data = mysqli_fetch_assoc($result_produk);
                                                                                                                        mysqli_stmt_close($stmt);

                                                                                                                            if (!$produk_data) {
                                                                                                                                    $response['message'] = 'Produk tidak ditemukan.';
                                                                                                                                            echo json_encode($response);
                                                                                                                                                    exit();
                                                                                                                                                        }

                                                                                                                                                            // Fungsi getEffectivePriceAndPromoStatus (duplikasi dari keranjang.php)
                                                                                                                                                                // Idealnya ini di file terpisah dan di-include
                                                                                                                                                                    function getEffectivePriceAndPromoStatus($product) {
                                                                                                                                                                            $harga_normal = $product['harga'];
                                                                                                                                                                                    $harga_diskon = $product['harga_diskon'];
                                                                                                                                                                                            $promo_mulai = $product['promo_mulai'];
                                                                                                                                                                                                    $promo_akhir = $product['promo_akhir'];
                                                                                                                                                                                                            $now = new DateTime();

                                                                                                                                                                                                                    $effective_price = $harga_normal;
                                                                                                                                                                                                                            $is_promo_active = false;

                                                                                                                                                                                                                                    if ($harga_diskon !== null && $harga_diskon < $harga_normal) {
                                                                                                                                                                                                                                                if ($promo_mulai && $promo_akhir) {
                                                                                                                                                                                                                                                                $start_date = new DateTime($promo_mulai);
                                                                                                                                                                                                                                                                                $end_date = new DateTime($promo_akhir);

                                                                                                                                                                                                                                                                                                if ($now >= $start_date && $now <= $end_date) {
                                                                                                                                                                                                                                                                                                                    $effective_price = $harga_diskon;
                                                                                                                                                                                                                                                                                                                                        $is_promo_active = true;
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                    $effective_price = $harga_diskon;
                                                                                                                                                                                                                                                                                                                                                                                                    $is_promo_active = true;
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                return ['price' => $effective_price, 'is_promo' => $is_promo_active];
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                        $promo_data = getEffectivePriceAndPromoStatus($produk_data);
                                                                                                                                                                                                                                                                                                                                                                                                                                            $harga_efektif = $promo_data['price'];

                                                                                                                                                                                                                                                                                                                                                                                                                                                if ($jumlah_baru === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Hapus produk dari keranjang jika jumlahnya 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                unset($_SESSION['keranjang'][$produk_id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Update jumlah produk di keranjang
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $_SESSION['keranjang'][$produk_id] = $jumlah_baru;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Hitung ulang total keranjang
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $total_harga_seluruh_keranjang = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    foreach ($_SESSION['keranjang'] as $id_produk_keranjang => $qty_produk_keranjang) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $query_item = "SELECT harga, harga_diskon, promo_mulai, promo_akhir FROM produk WHERE id = ?";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt_item = mysqli_prepare($koneksi, $query_item);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mysqli_stmt_bind_param($stmt_item, "i", $id_produk_keranjang);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mysqli_stmt_execute($stmt_item);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $result_item = mysqli_stmt_get_result($stmt_item);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $item_data = mysqli_fetch_assoc($result_item);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mysqli_stmt_close($stmt_item);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ($item_data) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $item_promo_data = getEffectivePriceAndPromoStatus($item_data);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $item_harga_efektif = $item_promo_data['price'];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $total_harga_seluruh_keranjang += ($item_harga_efektif * $qty_produk_keranjang);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $response['success'] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $response['new_quantity'] = $jumlah_baru;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $response['item_subtotal'] = $harga_efektif * $jumlah_baru;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $response['total_cart_price'] = $total_harga_seluruh_keranjang;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $response['message'] = 'Jumlah produk berhasil diperbarui.';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $response['message'] = 'Metode request tidak diizinkan.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo json_encode($response);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>