<?php
// /admin/proses_kategori.php
require_once '../config/database.php';

// Proteksi
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin' || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: /auth/login.php");
        exit();
        }

        // ---- BLOK TRY-CATCH GLOBAL UNTUK MENANGKAP SEMUA ERROR ----
        try {
            $action = $_POST['action'] ?? '';

                if ($action == 'tambah') {
                        $nama = trim($_POST['nama_kategori'] ?? '');
                                
                                        if (empty($nama)) {
                                                    throw new Exception("Nama kategori wajib diisi.");
                                                            }

                                                                    $icon_path_db = 'default.png'; // Default jika tidak ada ikon diunggah
                                                                            $target_dir = "../assets/img/icons/"; // Direktori penyimpanan ikon

                                                                                    // Proses upload ikon jika ada
                                                                                            if (isset($_FILES['icon_kategori']) && $_FILES['icon_kategori']['error'] === UPLOAD_ERR_OK) {
                                                                                                        if (!is_dir($target_dir)) {
                                                                                                                        if (!mkdir($target_dir, 0755, true)) {
                                                                                                                                            throw new Exception("Gagal membuat direktori ikon: " . error_get_last()['message']);
                                                                                                                                                            }
                                                                                                                                                                        }
                                                                                                                                                                                    $file_extension = strtolower(pathinfo($_FILES['icon_kategori']['name'], PATHINFO_EXTENSION));
                                                                                                                                                                                                $allowed_extensions = ['png', 'svg']; // Hanya izinkan PNG dan SVG
                                                                                                                                                                                                            if (!in_array($file_extension, $allowed_extensions)) {
                                                                                                                                                                                                                            throw new Exception("Format file ikon tidak didukung. Hanya PNG atau SVG yang diizinkan.");
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                    $nama_icon = uniqid() . '.' . $file_extension;
                                                                                                                                                                                                                                                                $target_file = $target_dir . $nama_icon;

                                                                                                                                                                                                                                                                            if (move_uploaded_file($_FILES['icon_kategori']["tmp_name"], $target_file)) {
                                                                                                                                                                                                                                                                                            $icon_path_db = '/assets/img/icons/' . $nama_icon; // Simpan jalur relatif untuk DB
                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                        throw new Exception("Gagal mengunggah file ikon.");
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                    $stmt = $koneksi->prepare("INSERT INTO kategori (nama_kategori, icon) VALUES (?, ?)");
                                                                                                                                                                                                                                                                                                                                                            if ($stmt === false) {
                                                                                                                                                                                                                                                                                                                                                                        // Hapus ikon yang terunggah jika prepare gagal
                                                                                                                                                                                                                                                                                                                                                                                    if (!empty($nama_icon) && file_exists($target_dir . $nama_icon)) {
                                                                                                                                                                                                                                                                                                                                                                                                    unlink($target_dir . $nama_icon);
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Exception("Sistem Error: Gagal menyiapkan query tambah kategori: " . $koneksi->error);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt->bind_param("ss", $nama, $icon_path_db);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ($stmt->execute()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        header("Location: kelola_kategori.php?status=sukses");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Hapus ikon yang terunggah jika execute gagal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!empty($nama_icon) && file_exists($target_dir . $nama_icon)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    unlink($target_dir . $nama_icon);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Exception("Gagal menyimpan kategori ke database: " . $stmt->error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt->close();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } elseif ($action == 'hapus') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $id = (int)$_POST['id'];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $icon_path_to_delete = $_POST['icon_path'] ?? ''; // Ambil path ikon dari hidden input

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Hapus kategori dari database
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $stmt = $koneksi->prepare("DELETE FROM kategori WHERE id = ?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($stmt === false) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    throw new Exception("Sistem Error: Gagal menyiapkan query hapus kategori: " . $koneksi->error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt->bind_param("i", $id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ($stmt->execute()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Hapus file ikon dari server jika bukan default.png
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!empty($icon_path_to_delete) && $icon_path_to_delete !== 'default.png') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $full_path = '..' . $icon_path_to_delete; // Sesuaikan path relatif
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (file_exists($full_path)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                unlink($full_path);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        header("Location: kelola_kategori.php?status=sukses");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        throw new Exception("Gagal menghapus kategori dari database: " . $stmt->error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $stmt->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    throw new Exception("Aksi tidak valid.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            error_log("Error in proses_kategori.php: " . $e->getMessage());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                header("Location: kelola_kategori.php?status=gagal&pesan=" . urlencode($e->getMessage()));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isset($koneksi) && $koneksi instanceof mysqli) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?>