<?php
// /penjual/proses_tambah_produk.php
require_once '../config/database.php';

// Fungsi bantuan untuk upload file
function upload_gambar_produk($file_input_name, $target_dir) {
    if (isset($_FILES[$file_input_name]) && $_FILES[$file_input_name]['error'] === UPLOAD_ERR_OK) {
            if (!is_dir($target_dir)) {
                        if (!mkdir($target_dir, 0755, true)) {
                                        throw new Exception("Gagal membuat direktori upload.");
                                                    }
                                                            }
                                                                    $nama_gambar = uniqid() . '-' . basename($_FILES[$file_input_name]["name"]);
                                                                            $target_file = $target_dir . $nama_gambar;
                                                                                    if (move_uploaded_file($_FILES[$file_input_name]["tmp_name"], $target_file)) {
                                                                                                return $nama_gambar;
                                                                                                        } else {
                                                                                                                    throw new Exception("Gagal mengunggah file {$file_input_name}.");
                                                                                                                            }
                                                                                                                                }
                                                                                                                                    return NULL; // Return NULL jika tidak ada file atau ada error
                                                                                                                                    }

                                                                                                                                    try {
                                                                                                                                        if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'penjual' || $_SERVER['REQUEST_METHOD'] !== 'POST') {
                                                                                                                                                header("Location: /auth/login.php");
                                                                                                                                                        exit();
                                                                                                                                                            }

                                                                                                                                                                // Ambil data form
                                                                                                                                                                    $nama_produk = trim($_POST['nama_produk']);
                                                                                                                                                                        $deskripsi = trim($_POST['deskripsi']);
                                                                                                                                                                            $harga = (float)$_POST['harga'];
                                                                                                                                                                                $stok = (int)$_POST['stok'];
                                                                                                                                                                                    $kategori_id = (int)$_POST['kategori_id'];
                                                                                                                                                                                        $jenis_produk = $_POST['jenis_produk'];
                                                                                                                                                                                            $berat = ($jenis_produk === 'fisik') ? (int)$_POST['berat'] : 0;
                                                                                                                                                                                                $link_digital = ($jenis_produk === 'digital') ? trim($_POST['link_digital']) : NULL;
                                                                                                                                                                                                    $user_id = $_SESSION['user_id'];
                                                                                                                                                                                                        
                                                                                                                                                                                                            $harga_diskon = isset($_POST['harga_diskon']) && $_POST['harga_diskon'] !== '' ? (float)$_POST['harga_diskon'] : NULL;
                                                                                                                                                                                                                $promo_mulai = isset($_POST['promo_mulai']) && $_POST['promo_mulai'] !== '' ? $_POST['promo_mulai'] : NULL;
                                                                                                                                                                                                                    $promo_akhir = isset($_POST['promo_akhir']) && $_POST['promo_akhir'] !== '' ? $_POST['promo_akhir'] : NULL;

                                                                                                                                                                                                                        // Ambil toko_id
                                                                                                                                                                                                                            $stmt_toko = $koneksi->prepare("SELECT id FROM toko WHERE user_id = ?");
                                                                                                                                                                                                                                $stmt_toko->bind_param("i", $user_id);
                                                                                                                                                                                                                                    $stmt_toko->execute();
                                                                                                                                                                                                                                        $toko = $stmt_toko->get_result()->fetch_assoc();
                                                                                                                                                                                                                                            $stmt_toko->close();
                                                                                                                                                                                                                                                if (!$toko) { throw new Exception("Profil toko tidak ditemukan."); }
                                                                                                                                                                                                                                                    $toko_id = $toko['id'];

                                                                                                                                                                                                                                                        // Proses upload semua gambar
                                                                                                                                                                                                                                                            $target_dir = "../uploads/produk/";
                                                                                                                                                                                                                                                                $nama_gambar_1 = upload_gambar_produk('gambar_produk', $target_dir);
                                                                                                                                                                                                                                                                    $nama_gambar_2 = upload_gambar_produk('gambar_produk_2', $target_dir);
                                                                                                                                                                                                                                                                        $nama_gambar_3 = upload_gambar_produk('gambar_produk_3', $target_dir);

                                                                                                                                                                                                                                                                            if ($nama_gambar_1 === NULL) {
                                                                                                                                                                                                                                                                                    throw new Exception("Gambar utama wajib diunggah.");
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                            // Masukkan data ke database
                                                                                                                                                                                                                                                                                                $stmt_insert = $koneksi->prepare(
                                                                                                                                                                                                                                                                                                        "INSERT INTO produk (toko_id, kategori_id, jenis_produk, nama_produk, deskripsi, harga, harga_diskon, promo_mulai, promo_akhir, stok, berat, gambar_produk, gambar_produk_2, gambar_produk_3, link_digital) 
                                                                                                                                                                                                                                                                                                                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                        $stmt_insert->bind_param(
                                                                                                                                                                                                                                                                                                                                "iisssddssiissss", 
                                                                                                                                                                                                                                                                                                                                        $toko_id, $kategori_id, $jenis_produk, $nama_produk, $deskripsi, $harga, $harga_diskon, $promo_mulai, $promo_akhir, $stok, $berat, $nama_gambar_1, $nama_gambar_2, $nama_gambar_3, $link_digital
                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                if ($stmt_insert->execute()) {
                                                                                                                                                                                                                                                                                                                                                        header("Location: produk_saya.php?status=sukses");
                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                    throw new Exception("Gagal menyimpan produk ke database: " . $stmt_insert->error);
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                            $stmt_insert->close();

                                                                                                                                                                                                                                                                                                                                                                            } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                header("Location: tambah_produk.php?status=gagal&pesan=" . urlencode($e->getMessage()));
                                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                                    if (isset($koneksi)) $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                        exit();
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                        ?>