<?php
// /proses_edit_profil.php (Versi dengan validasi password lama)

require_once 'config/database.php';

if (!isset($_SESSION['user_id']) || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: /auth/login.php");
        exit();
        }

        $user_id = $_SESSION['user_id'];

        // Ambil data dari form
        $email = trim($_POST['email']);
        $no_telepon = trim($_POST['no_telepon']);
        $password_lama = $_POST['password_lama'];
        $password_baru = $_POST['password_baru'];
        $konfirmasi_password = $_POST['konfirmasi_password'];
        $foto_profil_lama = $_POST['foto_profil_lama'];

        mysqli_begin_transaction($koneksi);

        try {
            // Validasi dasar
                if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                        throw new Exception("Format email tidak valid.");
                            }

                                // Cek duplikasi email (jika email diubah)
                                    $stmt_check_email = $koneksi->prepare("SELECT id FROM users WHERE email = ? AND id != ?");
                                        $stmt_check_email->bind_param("si", $email, $user_id);
                                            $stmt_check_email->execute();
                                                if ($stmt_check_email->get_result()->num_rows > 0) {
                                                        throw new Exception("Email sudah digunakan oleh akun lain.");
                                                            }
                                                                $stmt_check_email->close();

                                                                    // Proses upload foto profil
                                                                        $nama_foto_baru = $foto_profil_lama;
                                                                            if (isset($_FILES['foto_profil']) && $_FILES['foto_profil']['error'] === UPLOAD_ERR_OK) {
                                                                                    $file = $_FILES['foto_profil'];
                                                                                            $target_dir = "uploads/profil/";
                                                                                                    if (!is_dir($target_dir)) mkdir($target_dir, 0755, true);
                                                                                                            
                                                                                                                    $file_extension = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
                                                                                                                            $nama_foto_baru = "user_" . $user_id . "_" . time() . "." . $file_extension;
                                                                                                                                    $target_file = $target_dir . $nama_foto_baru;

                                                                                                                                            if (!move_uploaded_file($file['tmp_name'], $target_file)) {
                                                                                                                                                        throw new Exception("Gagal mengunggah foto profil.");
                                                                                                                                                                }

                                                                                                                                                                        if (!empty($foto_profil_lama) && file_exists($target_dir . $foto_profil_lama)) {
                                                                                                                                                                                    unlink($target_dir . $foto_profil_lama);
                                                                                                                                                                                            }
                                                                                                                                                                                                }

                                                                                                                                                                                                    // Siapkan query update dasar
                                                                                                                                                                                                        $query = "UPDATE users SET email = ?, no_telepon = ?, foto_profil = ?";
                                                                                                                                                                                                            $types = "sss";
                                                                                                                                                                                                                $params = [$email, $no_telepon, $nama_foto_baru];

                                                                                                                                                                                                                    // Proses password HANYA jika password baru diisi
                                                                                                                                                                                                                        if (!empty($password_baru)) {
                                                                                                                                                                                                                                if (empty($password_lama)) {
                                                                                                                                                                                                                                            throw new Exception("Untuk mengubah password, Anda harus memasukkan password lama Anda.");
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                            $stmt_get_pass = $koneksi->prepare("SELECT password FROM users WHERE id = ?");
                                                                                                                                                                                                                                                                    $stmt_get_pass->bind_param("i", $user_id);
                                                                                                                                                                                                                                                                            $stmt_get_pass->execute();
                                                                                                                                                                                                                                                                                    $current_user = $stmt_get_pass->get_result()->fetch_assoc();
                                                                                                                                                                                                                                                                                            $stmt_get_pass->close();

                                                                                                                                                                                                                                                                                                    if (!password_verify($password_lama, $current_user['password'])) {
                                                                                                                                                                                                                                                                                                                throw new Exception("Password lama yang Anda masukkan salah.");
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                if ($password_baru !== $konfirmasi_password) {
                                                                                                                                                                                                                                                                                                                                            throw new Exception("Konfirmasi password baru tidak cocok.");
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                            if (strlen($password_baru) < 6) {
                                                                                                                                                                                                                                                                                                                                                                        throw new Exception("Password minimal harus 6 karakter.");
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                $hashed_password = password_hash($password_baru, PASSWORD_DEFAULT);
                                                                                                                                                                                                                                                                                                                                                                                                        $query .= ", password = ?";
                                                                                                                                                                                                                                                                                                                                                                                                                $types .= "s";
                                                                                                                                                                                                                                                                                                                                                                                                                        $params[] = $hashed_password;
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                $query .= " WHERE id = ?";
                                                                                                                                                                                                                                                                                                                                                                                                                                    $types .= "i";
                                                                                                                                                                                                                                                                                                                                                                                                                                        $params[] = $user_id;

                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt_update = $koneksi->prepare($query);
                                                                                                                                                                                                                                                                                                                                                                                                                                                $stmt_update->bind_param($types, ...$params);

                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!$stmt_update->execute()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Exception("Gagal memperbarui profil: " . $stmt_update->error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt_update->close();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mysqli_commit($koneksi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            header("Location: profil_saya.php?status=sukses");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mysqli_rollback($koneksi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    header("Location: profil_saya.php?status=gagal&pesan=" . urlencode($e->getMessage()));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isset($koneksi)) $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>