<?php
// /admin/proses_pengaturan.php
require_once '../config/database.php';

// Proteksi
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin' || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: /auth/login.php");
        exit();
        }

        mysqli_begin_transaction($koneksi);

        try {
            $action = $_POST['action'] ?? '';

                if ($action === 'update_rekening') {
                        // Logika BARU untuk update rekening bank
                                $nama_bank = trim($_POST['nama_bank']);
                                        $nomor_rekening = trim($_POST['nomor_rekening']);
                                                $nama_pemilik = trim($_POST['nama_pemilik_rekening']);

                                                        if (empty($nama_bank) || empty($nomor_rekening) || empty($nama_pemilik)) {
                                                                    throw new Exception("Semua field rekening bank wajib diisi.");
                                                                            }

                                                                                    // Lakukan update untuk setiap pengaturan
                                                                                            $stmt1 = $koneksi->prepare("UPDATE pengaturan SET nilai_pengaturan = ? WHERE nama_pengaturan = 'nama_bank'");
                                                                                                    $stmt1->bind_param("s", $nama_bank);
                                                                                                            if (!$stmt1->execute()) throw new Exception("Gagal menyimpan nama bank.");
                                                                                                                    
                                                                                                                            $stmt2 = $koneksi->prepare("UPDATE pengaturan SET nilai_pengaturan = ? WHERE nama_pengaturan = 'nomor_rekening'");
                                                                                                                                    $stmt2->bind_param("s", $nomor_rekening);
                                                                                                                                            if (!$stmt2->execute()) throw new Exception("Gagal menyimpan nomor rekening.");
                                                                                                                                                    
                                                                                                                                                            $stmt3 = $koneksi->prepare("UPDATE pengaturan SET nilai_pengaturan = ? WHERE nama_pengaturan = 'nama_pemilik_rekening'");
                                                                                                                                                                    $stmt3->bind_param("s", $nama_pemilik);
                                                                                                                                                                            if (!$stmt3->execute()) throw new Exception("Gagal menyimpan nama pemilik rekening.");
                                                                                                                                                                                    
                                                                                                                                                                                        } elseif ($action === 'update_qris') {
                                                                                                                                                                                                // Logika BARU untuk update QRIS
                                                                                                                                                                                                        if (!isset($_FILES['qris_image']) || $_FILES['qris_image']['error'] !== UPLOAD_ERR_OK) {
                                                                                                                                                                                                                    // Jika tidak ada file baru diunggah, tidak perlu lakukan apa-apa. Anggap sukses.
                                                                                                                                                                                                                                header("Location: kelola_pengaturan.php?status=sukses");
                                                                                                                                                                                                                                            exit();
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                    $qris_lama = $_POST['qris_lama'];
                                                                                                                                                                                                                                                                            $file = $_FILES['qris_image'];
                                                                                                                                                                                                                                                                                    $target_dir = "../uploads/qris/";

                                                                                                                                                                                                                                                                                            if (!is_dir($target_dir)) {
                                                                                                                                                                                                                                                                                                        mkdir($target_dir, 0755, true);
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                        $file_extension = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
                                                                                                                                                                                                                                                                                                                                $nama_file_baru = "qris_" . time() . "." . $file_extension;
                                                                                                                                                                                                                                                                                                                                        $target_file = $target_dir . $nama_file_baru;

                                                                                                                                                                                                                                                                                                                                                if (!move_uploaded_file($file['tmp_name'], $target_file)) {
                                                                                                                                                                                                                                                                                                                                                            throw new Exception("Gagal memindahkan file QRIS yang diunggah.");
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                    $path_db_baru = "/uploads/qris/" . $nama_file_baru;

                                                                                                                                                                                                                                                                                                                                                                                            // Hapus file lama jika bukan default
                                                                                                                                                                                                                                                                                                                                                                                                    $path_lama_fisik = ".." . $qris_lama;
                                                                                                                                                                                                                                                                                                                                                                                                            if ($qris_lama !== '/uploads/qris/default_qris.png' && file_exists($path_lama_fisik)) {
                                                                                                                                                                                                                                                                                                                                                                                                                        unlink($path_lama_fisik);
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                        $stmt = $koneksi->prepare("UPDATE pengaturan SET nilai_pengaturan = ? WHERE nama_pengaturan = 'qris_image'");
                                                                                                                                                                                                                                                                                                                                                                                                                                                $stmt->bind_param("s", $path_db_baru);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!$stmt->execute()) throw new Exception("Gagal menyimpan path QRIS ke database.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Logika lama untuk pengaturan lain
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $pengaturan_map = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'update_komisi' => ['nama' => 'persentase_komisi', 'post_field' => 'persentase_komisi'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'update_nama_website' => ['nama' => 'nama_website', 'post_field' => 'nama_website'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'update_logo' => ['nama' => 'website_logo', 'post_field' => 'website_logo', 'is_file' => true]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!array_key_exists($action, $pengaturan_map)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Exception("Aksi tidak valid.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $config = $pengaturan_map[$action];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Jika ini adalah aksi untuk file (logo)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (isset($config['is_file']) && $config['is_file']) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isset($_FILES[$config['post_field']]) && $_FILES[$config['post_field']]['error'] === UPLOAD_ERR_OK) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $file = $_FILES[$config['post_field']];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $target_dir = "../uploads/logo/";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!is_dir($target_dir)) mkdir($target_dir, 0755, true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $file_extension = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $nama_file_baru = "logo_" . time() . "." . $file_extension;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $target_file = $target_dir . $nama_file_baru;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!move_uploaded_file($file['tmp_name'], $target_file)) throw new Exception("Gagal unggah logo.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $nilai_baru = "/uploads/logo/" . $nama_file_baru;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Hapus logo lama
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $logo_lama = $_POST['logo_lama'];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $path_lama_fisik = ".." . $logo_lama;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($logo_lama !== '/uploads/logo/default_logo.png' && file_exists($path_lama_fisik)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            unlink($path_lama_fisik);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt = $koneksi->prepare("UPDATE pengaturan SET nilai_pengaturan = ? WHERE nama_pengaturan = ?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt->bind_param("ss", $nilai_baru, $config['nama']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!$stmt->execute()) throw new Exception("Gagal simpan logo baru.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } // Jika tidak ada file baru, tidak perlu lakukan apa-apa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Jika ini aksi untuk data teks biasa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $nilai_baru = trim($_POST[$config['post_field']]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ($nilai_baru === '') throw new Exception("Nilai tidak boleh kosong.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt = $koneksi->prepare("UPDATE pengaturan SET nilai_pengaturan = ? WHERE nama_pengaturan = ?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $stmt->bind_param("ss", $nilai_baru, $config['nama']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!$stmt->execute()) throw new Exception("Gagal menyimpan pengaturan.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mysqli_commit($koneksi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        header("Location: kelola_pengaturan.php?status=sukses");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mysqli_rollback($koneksi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                error_log("Error in proses_pengaturan.php: " . $e->getMessage());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    header("Location: kelola_pengaturan.php?status=gagal&pesan=" . urlencode($e->getMessage()));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isset($koneksi) && $koneksi instanceof mysqli) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?>