<?php
// /admin/proses_aksi_massal.php
require_once '../config/database.php'; // Pastikan path ini benar
require_once 'proses_konfirmasi_pembayaran.php'; // Sertakan file yang berisi fungsi konfirmasi

// Proteksi: Pastikan user adalah admin dan request adalah POST
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin' || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: /auth/login.php");
        exit();
        }

        $action = $_POST['action'] ?? '';
        $pesanan_ids = $_POST['pesanan_ids'] ?? []; // Ini akan menjadi array ID pesanan yang dicentang

        $berhasil_diproses = 0;
        $gagal_diproses = 0;
        $pesan_error_detail = [];

        if (empty($pesanan_ids) || !is_array($pesanan_ids)) {
            header("Location: kelola_pesanan.php?status=gagal&pesan=" . urlencode("Tidak ada pesanan yang dipilih atau data tidak valid."));
                exit();
                }

                // Mulai transaksi database untuk seluruh aksi massal
                mysqli_begin_transaction($koneksi);

                try {
                    foreach ($pesanan_ids as $pesanan_id) {
                            $pesanan_id = (int)$pesanan_id; // Pastikan ID adalah integer

                                    // Hanya proses jika aksi yang diminta adalah konfirmasi pembayaran massal
                                            if ($action === 'konfirmasi_massal') {
                                                        // Kita perlu mencari ID pembayaran yang terkait dengan pesanan ini.
                                                                    // Asumsi: ada satu pembayaran per pesanan, dan statusnya 'menunggu' untuk dikonfirmasi.
                                                                                $stmt_pembayaran_id = $koneksi->prepare("SELECT id FROM pembayaran WHERE pesanan_id = ? AND status_konfirmasi = 'menunggu'");
                                                                                            if ($stmt_pembayaran_id === false) {
                                                                                                            throw new Exception("Sistem Error: Gagal menyiapkan query cari pembayaran: " . $koneksi->error);
                                                                                                                        }
                                                                                                                                    $stmt_pembayaran_id->bind_param("i", $pesanan_id);
                                                                                                                                                $stmt_pembayaran_id->execute();
                                                                                                                                                            $result_pembayaran_id = $stmt_pembayaran_id->get_result();
                                                                                                                                                                        $pembayaran_data = $result_pembayaran_id->fetch_assoc();
                                                                                                                                                                                    $stmt_pembayaran_id->close();

                                                                                                                                                                                                if ($pembayaran_data) {
                                                                                                                                                                                                                $pembayaran_id = (int)$pembayaran_data['id'];
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                    // Panggil fungsi konfirmasi individual yang sudah kita buat
                                                                                                                                                                                                                                                                                        prosesKonfirmasiPembayaranIndividual($koneksi, $pesanan_id, $pembayaran_id, 'konfirmasi');
                                                                                                                                                                                                                                                                                                            $berhasil_diproses++;
                                                                                                                                                                                                                                                                                                                            } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                $gagal_diproses++;
                                                                                                                                                                                                                                                                                                                                                                    $pesan_error_detail[] = "Pesanan #{$pesanan_id} GAGAL dikonfirmasi: " . $e->getMessage();
                                                                                                                                                                                                                                                                                                                                                                                        // Log error untuk debugging internal
                                                                                                                                                                                                                                                                                                                                                                                                            error_log("Massal Konfirmasi Gagal untuk Pesanan #{$pesanan_id}: " . $e->getMessage());
                                                                                                                                                                                                                                                                                                                                                                                                                                // Lanjutkan ke pesanan berikutnya, jangan hentikan seluruh transaksi
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $gagal_diproses++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $pesan_error_detail[] = "Pesanan #{$pesanan_id} GAGAL: Pembayaran tidak ditemukan atau sudah dikonfirmasi/ditolak.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Commit transaksi jika semua iterasi berhasil atau beberapa gagal (tapi tidak membatalkan yang lain)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mysqli_commit($koneksi);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Siapkan pesan redirect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $pesan_sukses = "Aksi massal berhasil memproses {$berhasil_diproses} pesanan.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($gagal_diproses > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $pesan_sukses .= " ({$gagal_diproses} pesanan gagal: " . implode("; ", $pesan_error_detail) . ")";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        header("Location: kelola_pesanan.php?status=gagal_massal&pesan=" . urlencode($pesan_sukses));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    header("Location: kelola_pesanan.php?status=sukses_massal&sukses=" . $berhasil_diproses);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            exit();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Rollback seluruh transaksi jika ada error fatal di luar loop (misalnya masalah koneksi)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mysqli_rollback($koneksi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        error_log("Error fatal di proses_aksi_massal.php: " . $e->getMessage());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            header("Location: kelola_pesanan.php?status=gagal&pesan=" . urlencode("Terjadi kesalahan fatal: " . $e->getMessage()));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (isset($koneksi) && $koneksi instanceof mysqli) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>