<?php
require_once '../config/database.php';

// Proteksi
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin' || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: /auth/login.php");
        exit();
        }

        $action = $_POST['action'] ?? '';

        try {
            if ($action === 'tambah') {
                    $kurir = trim($_POST['kurir']);
                            $provinsi = trim(strtoupper($_POST['provinsi']));
                                    $kota = trim(strtoupper($_POST['kota']));
                                            $kecamatan = empty(trim($_POST['kecamatan'])) ? NULL : trim(strtoupper($_POST['kecamatan']));
                                                    $biaya = (float)$_POST['biaya'];
                                                            $estimasi = trim($_POST['estimasi']);

                                                                    if (empty($kurir) || empty($provinsi) || empty($kota) || $biaya < 0) {
                                                                                throw new Exception("Data tidak lengkap.");
                                                                                        }

                                                                                                $stmt = $koneksi->prepare("INSERT INTO ongkos_kirim (kurir, provinsi, kota, kecamatan, biaya, estimasi) VALUES (?, ?, ?, ?, ?, ?)");
                                                                                                        $stmt->bind_param("ssssds", $kurir, $provinsi, $kota, $kecamatan, $biaya, $estimasi);
                                                                                                                if (!$stmt->execute()) {
                                                                                                                            throw new Exception("Gagal menyimpan data: " . $stmt->error);
                                                                                                                                    }
                                                                                                                                            $stmt->close();
                                                                                                                                                    header("Location: kelola_ongkir.php?status=sukses&pesan=Tarif berhasil ditambahkan.");

                                                                                                                                                        } elseif ($action === 'edit') {
                                                                                                                                                                // LOGIKA BARU UNTUK EDIT
                                                                                                                                                                        $id = (int)$_POST['id'];
                                                                                                                                                                                $kurir = trim($_POST['kurir']);
                                                                                                                                                                                        $provinsi = trim(strtoupper($_POST['provinsi']));
                                                                                                                                                                                                $kota = trim(strtoupper($_POST['kota']));
                                                                                                                                                                                                        $kecamatan = empty(trim($_POST['kecamatan'])) ? NULL : trim(strtoupper($_POST['kecamatan']));
                                                                                                                                                                                                                $biaya = (float)$_POST['biaya'];
                                                                                                                                                                                                                        $estimasi = trim($_POST['estimasi']);

                                                                                                                                                                                                                                if ($id <= 0 || empty($kurir) || empty($provinsi) || empty($kota) || $biaya < 0) {
                                                                                                                                                                                                                                            throw new Exception("Data tidak lengkap.");
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                            $stmt = $koneksi->prepare("UPDATE ongkos_kirim SET kurir=?, provinsi=?, kota=?, kecamatan=?, biaya=?, estimasi=? WHERE id=?");
                                                                                                                                                                                                                                                                    $stmt->bind_param("ssssdsi", $kurir, $provinsi, $kota, $kecamatan, $biaya, $estimasi, $id);
                                                                                                                                                                                                                                                                            if (!$stmt->execute()) {
                                                                                                                                                                                                                                                                                        throw new Exception("Gagal memperbarui data: " . $stmt->error);
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                        $stmt->close();
                                                                                                                                                                                                                                                                                                                header("Location: kelola_ongkir.php?status=sukses&pesan=Tarif berhasil diperbarui.");

                                                                                                                                                                                                                                                                                                                    } elseif ($action === 'hapus') {
                                                                                                                                                                                                                                                                                                                            $id = (int)$_POST['id'];
                                                                                                                                                                                                                                                                                                                                    $stmt = $koneksi->prepare("DELETE FROM ongkos_kirim WHERE id = ?");
                                                                                                                                                                                                                                                                                                                                            $stmt->bind_param("i", $id);
                                                                                                                                                                                                                                                                                                                                                    if (!$stmt->execute()) {
                                                                                                                                                                                                                                                                                                                                                                throw new Exception("Gagal menghapus data: " . $stmt->error);
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                $stmt->close();
                                                                                                                                                                                                                                                                                                                                                                                        header("Location: kelola_ongkir.php?status=sukses&pesan=Tarif berhasil dihapus.");

                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                    throw new Exception("Aksi tidak valid.");
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                            header("Location: kelola_ongkir.php?status=gagal&pesan=" . urlencode($e->getMessage()));
                                                                                                                                                                                                                                                                                                                                                                                                            } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                if (isset($koneksi)) $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                    exit();
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                    ?>