<?php
// /admin/proses_konfirmasi_pembayaran.php
require_once '../config/database.php';

// Proteksi
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin' || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: /auth/login.php");
        exit();
        }

        $pembayaran_id = (int)$_POST['pembayaran_id'];
        $pesanan_id = (int)$_POST['pesanan_id'];
        $action = $_POST['action'];
        $admin_konfirmator_id = $_SESSION['user_id'];

        if ($action == 'konfirmasi') {
            $status_pembayaran = 'dikonfirmasi';
                $status_pesanan = 'diproses';
                } elseif ($action == 'tolak') {
                    $status_pembayaran = 'ditolak';
                        $status_pesanan = 'menunggu_pembayaran';
                        } else {
                            header("Location: kelola_pesanan.php");
                                exit();
                                }

                                mysqli_begin_transaction($koneksi);

                                try {
                                    // 1. Update status di tabel 'pembayaran'
                                        $stmt_bayar = $koneksi->prepare("UPDATE pembayaran SET status_konfirmasi = ? WHERE id = ?");
                                            if (!$stmt_bayar) throw new Exception("Prepare statement pembayaran gagal: " . $koneksi->error);
                                                $stmt_bayar->bind_param("si", $status_pembayaran, $pembayaran_id);
                                                    if (!$stmt_bayar->execute()) throw new Exception("Update pembayaran gagal: " . $stmt_bayar->error);
                                                        $stmt_bayar->close();

                                                            // 2. Update status & admin konfirmasi di tabel 'pesanan'
                                                                $stmt_pesan = $koneksi->prepare("UPDATE pesanan SET status_pesanan = ?, admin_konfirmasi_id = ? WHERE id = ?");
                                                                    if (!$stmt_pesan) throw new Exception("Prepare statement pesanan gagal: " . $koneksi->error);
                                                                        $stmt_pesan->bind_param("sii", $status_pesanan, $admin_konfirmator_id, $pesanan_id);
                                                                            if (!$stmt_pesan->execute()) throw new Exception("Update pesanan gagal: " . $stmt_pesan->error);
                                                                                $stmt_pesan->close();

                                                                                    // 3. Jika aksi adalah KONFIRMASI, kurangi stok produk
                                                                                        if ($action == 'konfirmasi') {
                                                                                                // Ambil semua produk dan jumlahnya dalam pesanan ini
                                                                                                        $stmt_get_items = $koneksi->prepare("SELECT produk_id, jumlah FROM detail_pesanan WHERE pesanan_id = ?");
                                                                                                                if (!$stmt_get_items) throw new Exception("Prepare statement get items gagal: " . $koneksi->error);
                                                                                                                        $stmt_get_items->bind_param("i", $pesanan_id);
                                                                                                                                $stmt_get_items->execute();
                                                                                                                                        $items_result = $stmt_get_items->get_result();
                                                                                                                                                
                                                                                                                                                        // Siapkan statement untuk update stok (akan digunakan berulang kali)
                                                                                                                                                                $stmt_update_stok = $koneksi->prepare("UPDATE produk SET stok = stok - ? WHERE id = ?");
                                                                                                                                                                        if (!$stmt_update_stok) throw new Exception("Prepare statement update stok gagal: " . $koneksi->error);

                                                                                                                                                                                while ($item = $items_result->fetch_assoc()) {
                                                                                                                                                                                            $stmt_update_stok->bind_param("ii", $item['jumlah'], $item['produk_id']);
                                                                                                                                                                                                        if (!$stmt_update_stok->execute()) {
                                                                                                                                                                                                                        throw new Exception("Gagal mengurangi stok untuk produk ID " . $item['produk_id'] . ": " . $stmt_update_stok->error);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                    $stmt_get_items->close();
                                                                                                                                                                                                                                                            $stmt_update_stok->close();

                                                                                                                                                                                                                                                                    // Kirim notifikasi ke penjual (logika ini sudah ada dan benar)
                                                                                                                                                                                                                                                                            $query_penjual = "SELECT DISTINCT t.user_id FROM toko t JOIN produk pr ON t.id = pr.toko_id JOIN detail_pesanan dp ON pr.id = dp.produk_id WHERE dp.pesanan_id = ?";
                                                                                                                                                                                                                                                                                    $stmt_cari_penjual = $koneksi->prepare($query_penjual);
                                                                                                                                                                                                                                                                                            $stmt_cari_penjual->bind_param("i", $pesanan_id);
                                                                                                                                                                                                                                                                                                    $stmt_cari_penjual->execute();
                                                                                                                                                                                                                                                                                                            $result_penjual = $stmt_cari_penjual->get_result();
                                                                                                                                                                                                                                                                                                                    $stmt_cari_penjual->close();
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                    $judul_notif = "Pesanan Baru!";
                                                                                                                                                                                                                                                                                                                                            $pesan_notif = "Pesanan #$pesanan_id telah dibayar dan perlu Anda proses.";
                                                                                                                                                                                                                                                                                                                                                    $link_notif = "/penjual/pesanan_masuk.php";
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                    $stmt_ins_notif = $koneksi->prepare("INSERT INTO notifikasi (user_id, judul, pesan, link, tipe) VALUES (?, ?, ?, ?, 'penjual')");
                                                                                                                                                                                                                                                                                                                                                                            while($penjual = $result_penjual->fetch_assoc()){
                                                                                                                                                                                                                                                                                                                                                                                        $penjual_id = $penjual['user_id'];
                                                                                                                                                                                                                                                                                                                                                                                                    $stmt_ins_notif->bind_param("isss", $penjual_id, $judul_notif, $pesan_notif, $link_notif);
                                                                                                                                                                                                                                                                                                                                                                                                                $stmt_ins_notif->execute();
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                $stmt_ins_notif->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                        mysqli_commit($koneksi);
                                                                                                                                                                                                                                                                                                                                                                                                                                            header("Location: detail_pesanan_admin.php?id=$pesanan_id&status=sukses");

                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                mysqli_rollback($koneksi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    error_log("Error in proses_konfirmasi_pembayaran.php: " . $e->getMessage());
                                                                                                                                                                                                                                                                                                                                                                                                                                                        header("Location: detail_pesanan_admin.php?id=$pesanan_id&status=gagal&pesan=" . urlencode($e->getMessage()));
                                                                                                                                                                                                                                                                                                                                                                                                                                                        } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (isset($koneksi) && $koneksi instanceof mysqli) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $koneksi->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>