<?php
$page_title = "Buat Password Baru";
require_once '../config/database.php';
require_once '../includes/header_auth.php';

$token = $_GET['token'] ?? '';
$is_valid = false;

if (!empty($token)) {
    $stmt = $koneksi->prepare("SELECT * FROM password_resets WHERE token = ? AND expires_at > NOW()");
        $stmt->bind_param("s", $token);
            $stmt->execute();
                if ($stmt->get_result()->num_rows > 0) {
                        $is_valid = true;
                            }
                                $stmt->close();
                                }
                                ?>
                                <div class="container mt-5">
                                    <div class="row justify-content-center">
                                            <div class="col-md-6 col-lg-4">
                                                        <div class="card shadow-sm">
                                                                        <div class="card-header text-center">
                                                                                            <h3>Buat Password Baru</h3>
                                                                                                            </div>
                                                                                                                            <div class="card-body">
                                                                                                                                                <?php if ($is_valid): ?>
                                                                                                                                                                        <form action="proses_reset_password.php" method="POST">
                                                                                                                                                                                                    <input type="hidden" name="token" value="<?php echo htmlspecialchars($token); ?>">
                                                                                                                                                                                                                                <div class="mb-3">
                                                                                                                                                                                                                                                                <label for="password_baru" class="form-label">Password Baru</label>
                                                                                                                                                                                                                                                                                                <input type="password" name="password_baru" id="password_baru" class="form-control" required>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                        <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                        <label for="konfirmasi_password" class="form-label">Konfirmasi Password Baru</label>
                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="password" name="konfirmasi_password" id="konfirmasi_password" class="form-control" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="d-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn btn-primary">Reset Password</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="alert alert-danger">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Link reset password tidak valid, sudah digunakan, atau telah kedaluwarsa. Silakan ulangi permintaan.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="text-center mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="lupa_password.php">Minta Link Baru</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php require_once '../includes/footer_auth.php'; ?>