<?php
// /penjual/riwayat_keuangan.php
$page_title = "Riwayat Keuangan";
require_once '../includes/header_penjual.php';

$user_id = $_SESSION['user_id'];

// Ambil toko_id
$stmt_toko = $koneksi->prepare("SELECT id FROM toko WHERE user_id = ?");
$stmt_toko->bind_param("i", $user_id);
$stmt_toko->execute();
$toko = $stmt_toko->get_result()->fetch_assoc();
$toko_id = $toko['id'];
$stmt_toko->close();

if (!$toko_id) {
    echo '<div class="alert alert-danger">Profil toko tidak ditemukan.</div>';
        require_once '../includes/footer_penjual.php';
            exit();
            }

            // Ambil riwayat transaksi
            $query_riwayat = "SELECT * FROM riwayat_transaksi_penjual WHERE toko_id = ? ORDER BY tanggal_transaksi DESC";
            $stmt_riwayat = $koneksi->prepare($query_riwayat);
            $stmt_riwayat->bind_param("i", $toko_id);
            $stmt_riwayat->execute();
            $result_riwayat = $stmt_riwayat->get_result();
            ?>

            <h1>Riwayat Keuangan Toko</h1>
            <hr>

            <div class="card shadow-sm">
                <div class="card-body">
                        <div class="table-responsive">
                                    <table class="table table-bordered table-hover">
                                                    <thead class="table-light">
                                                                        <tr>
                                                                                                <th>Tanggal</th>
                                                                                                                        <th>Jenis Transaksi</th>
                                                                                                                                                <th>Jumlah</th>
                                                                                                                                                                        <th>Deskripsi</th>
                                                                                                                                                                                            </tr>
                                                                                                                                                                                                            </thead>
                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                <?php if ($result_riwayat->num_rows > 0): ?>
                                                                                                                                                                                                                                                                        <?php while($riwayat = $result_riwayat->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                                    <td><?php echo date('d M Y H:i', strtotime($riwayat['tanggal_transaksi'])); ?></td>
                                                                                                                                                                                                                                                                                                                                                                    <td>
                                                                                                                                                                                                                                                                                                                                                                                                        <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                            $jenis_transaksi = $riwayat['jenis_transaksi'];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $badge_class = ($jenis_transaksi == 'masuk') ? 'bg-success' : 'bg-danger';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo '<span class="badge ' . $badge_class . '">' . ucfirst($jenis_transaksi) . '</span>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td class="<?php echo ($jenis_transaksi == 'masuk') ? 'text-success' : 'text-danger'; ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Rp <?php echo number_format($riwayat['jumlah'], 0, ',', '.'); ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php echo nl2br(htmlspecialchars($riwayat['deskripsi'])); ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr><td colspan="4" class="text-center">Belum ada riwayat transaksi.</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $stmt_riwayat->close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            require_once '../includes/footer_penjual.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>