<?php
// /admin/saldo_admin.php
$page_title = "Saldo & Laporan Keuangan";
require_once '../includes/header_admin.php';

// Ambil Saldo Admin Saat Ini
$saldo_res = $koneksi->query("SELECT nilai_pengaturan FROM pengaturan WHERE nama_pengaturan = 'saldo_admin'");
$saldo_admin = ($saldo_res && $saldo_res->num_rows > 0) ? (float)$saldo_res->fetch_assoc()['nilai_pengaturan'] : 0;

// Hitung Total Pemasukan (Komisi)
$pemasukan_res = $koneksi->query("SELECT SUM(jumlah) as total FROM riwayat_transaksi_admin WHERE jenis_transaksi = 'komisi_masuk'");
$total_pemasukan = ($pemasukan_res) ? (float)$pemasukan_res->fetch_assoc()['total'] : 0;

// Hitung Total Pengeluaran (Penarikan yang disetujui)
$pengeluaran_res = $koneksi->query("SELECT SUM(jumlah) as total FROM riwayat_transaksi_admin WHERE jenis_transaksi = 'penarikan_seller_selesai'");
$total_pengeluaran = ($pengeluaran_res) ? (float)$pengeluaran_res->fetch_assoc()['total'] : 0;

// Ambil Riwayat Transaksi
$result_riwayat = $koneksi->query("SELECT * FROM riwayat_transaksi_admin ORDER BY tanggal_transaksi DESC LIMIT 100");

?>

<h1>Saldo & Laporan Keuangan Admin</h1>
<hr>

<div class="row">
    <div class="col-lg-4">
            <div class="card text-white bg-primary mb-3">
                        <div class="card-header">Saldo Saat Ini</div>
                                    <div class="card-body">
                                                    <h4 class="card-title">Rp <?php echo number_format($saldo_admin, 2, ',', '.'); ?></h4>
                                                                </div>
                                                                        </div>
                                                                            </div>
                                                                                <div class="col-lg-4">
                                                                                        <div class="card text-white bg-success mb-3">
                                                                                                    <div class="card-header">Total Pemasukan (Komisi)</div>
                                                                                                                <div class="card-body">
                                                                                                                                <h4 class="card-title">Rp <?php echo number_format($total_pemasukan, 2, ',', '.'); ?></h4>
                                                                                                                                            </div>
                                                                                                                                                    </div>
                                                                                                                                                        </div>
                                                                                                                                                            <div class="col-lg-4">
                                                                                                                                                                    <div class="card text-white bg-danger mb-3">
                                                                                                                                                                                <div class="card-header">Total Pengeluaran (Penarikan)</div>
                                                                                                                                                                                            <div class="card-body">
                                                                                                                                                                                                            <h4 class="card-title">Rp <?php echo number_format($total_pengeluaran, 2, ',', '.'); ?></h4>
                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                    <div class="card shadow-sm mt-4">
                                                                                                                                                                                                                                        <div class="card-header">
                                                                                                                                                                                                                                                <h5>Riwayat Transaksi Terakhir</h5>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                        <div class="card-body">
                                                                                                                                                                                                                                                                <div class="table-responsive">
                                                                                                                                                                                                                                                                            <table class="table table-hover">
                                                                                                                                                                                                                                                                                            <thead class="table-light">
                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                        <th>Tanggal</th>
                                                                                                                                                                                                                                                                                                                                                                <th>Jenis Transaksi</th>
                                                                                                                                                                                                                                                                                                                                                                                        <th>Jumlah</th>
                                                                                                                                                                                                                                                                                                                                                                                                                <th>Deskripsi</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Referensi ID</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php if ($result_riwayat && $result_riwayat->num_rows > 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php while($trx = $result_riwayat->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td><?php echo date('d M Y H:i', strtotime($trx['tanggal_transaksi'])); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $jenis = $trx['jenis_transaksi'];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $badge = 'bg-secondary';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ($jenis == 'komisi_masuk') $badge = 'bg-success';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ($jenis == 'penarikan_seller_selesai') $badge = 'bg-danger';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo '<span class="badge ' . $badge . '">' . ucwords(str_replace('_', ' ', $jenis)) . '</span>';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td class="<?php echo ($jenis == 'komisi_masuk') ? 'text-success' : 'text-danger'; ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php echo ($jenis == 'komisi_masuk') ? '+' : '-'; ?> Rp <?php echo number_format($trx['jumlah'], 2, ',', '.'); ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td><?php echo htmlspecialchars($trx['deskripsi']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>#<?php echo $trx['referensi_id']; ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr><td colspan="5" class="text-center">Belum ada transaksi.</td></tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php require_once '../includes/footer_admin.php'; ?>