<?php
// /penjual/tambah_voucher.php
$page_title = "Tambah Voucher Baru";
require_once '../includes/header_penjual.php';

// Proteksi: Pastikan user adalah penjual
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'penjual') {
    header("Location: /auth/login.php");
        exit();
        }
        ?>

        <h1>Tambah Voucher Baru</h1>
        <hr>

        <div class="card shadow-sm">
            <div class="card-body">
                    <form action="proses_voucher.php" method="POST">
                                <input type="hidden" name="action" value="tambah">

                                            <div class="mb-3">
                                                            <label for="kode" class="form-label">Kode Voucher</label>
                                                                            <input type="text" class="form-control" id="kode" name="kode" required maxlength="50" placeholder="Contoh: PROMO10">
                                                                                            <small class="form-text text-muted">Kode unik yang akan dimasukkan pembeli.</small>
                                                                                                        </div>
                                                                                                                    <div class="mb-3">
                                                                                                                                    <label for="nilai_diskon" class="form-label">Nilai Diskon (%)</label>
                                                                                                                                                    <input type="number" class="form-control" id="nilai_diskon" name="nilai_diskon" min="1" max="100" step="0.01" required>
                                                                                                                                                                    <small class="form-text text-muted">Masukkan angka persentase diskon, contoh: 10 untuk 10%.</small>
                                                                                                                                                                                </div>
                                                                                                                                                                                            <div class="mb-3">
                                                                                                                                                                                                            <label for="min_pembelian" class="form-label">Minimum Pembelian (Rp) <small class="text-muted">(Opsional)</small></label>
                                                                                                                                                                                                                            <input type="number" class="form-control" id="min_pembelian" name="min_pembelian" min="0" step="0.01" placeholder="Contoh: 50000">
                                                                                                                                                                                                                                            <small class="form-text text-muted">Jumlah belanja minimum agar voucher dapat digunakan.</small>
                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                    <div class="row">
                                                                                                                                                                                                                                                                                    <div class="col-md-6 mb-3">
                                                                                                                                                                                                                                                                                                        <label for="tanggal_mulai" class="form-label">Berlaku Dari</label>
                                                                                                                                                                                                                                                                                                                            <input type="datetime-local" class="form-control" id="tanggal_mulai" name="tanggal_mulai" required>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                            <div class="col-md-6 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                <label for="tanggal_akhir" class="form-label">Berlaku Sampai</label>
                                                                                                                                                                                                                                                                                                                                                                                                    <input type="datetime-local" class="form-control" id="tanggal_akhir" name="tanggal_akhir" required>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label for="jumlah_penggunaan_total" class="form-label">Jumlah Penggunaan Total <small class="text-muted">(Opsional)</small></label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input type="number" class="form-control" id="jumlah_penggunaan_total" name="jumlah_penggunaan_total" min="1" placeholder="Contoh: 100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <small class="form-text text-muted">Batas total penggunaan voucher ini oleh semua pembeli.</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label for="limit_per_pembeli" class="form-label">Batas Penggunaan Per Pembeli <small class="text-muted">(Opsional, default 1x)</small></label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="number" class="form-control" id="limit_per_pembeli" name="limit_per_pembeli" min="1" placeholder="Contoh: 1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <small class="form-text text-muted">Batas penggunaan voucher ini oleh satu pembeli (misal: 1 untuk sekali pakai).</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" class="btn btn-primary">Simpan Voucher</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="kelola_voucher.php" class="btn btn-secondary">Batal</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php require_once '../includes/footer_penjual.php'; ?>